
proxy:
  title: SMC 40 Proxy
  port: 8080
  logo-url: https://raw.githubusercontent.com/bouldermaettel/A848/main/data/SMC40%208.jpg
  authentication: simple
  admin-groups: admins
  landing-page: /
  users:
  - name: matthias.mueller@swissmedic.ch
    password: Mamu1379
    groups: admins
  docker:
      internal-networking: true
  specs:
  - id: shinypython
    display-name: Shiny App with python and R
    description: App to test the orchestration of R & Python environment
    container-cmd: ["R", "-e", "shiny::runApp('/root/app')"]
    logo-url: https://raw.githubusercontent.com/bouldermaettel/A848/main/data/shiny_python.png
    container-image: shiny-python-app
    access-groups: admins
    container-network: virtual-net
  - id: duplicatefinder
    display-name: A848 for duplicate analysis
    description: App to detect duplicates
    container-cmd: [ "R", "-e", "shiny::runApp('/root/app')" ]
    logo-url: https://raw.githubusercontent.com/bouldermaettel/A848/main/data/prntscreen.png
    container-image: duplicate-finder
    access-groups: admins
    container-network: virtual-net

logging:
  file:
    shinyproxy.log