version: '3.8'

networks:
  sp-net:
    name: sp-net
services:
  neraa:
    container_name: neraa
    image: bouldermaettel/neraa
    restart: always
    networks:
      - sp-net
  shinyproxy:
    container_name: sp-neraa-a848
    build: ./shinyproxy
    ports:
      - 8080:8080
    restart: always
    environment:
      - "WORK_DIR=${PWD}"
    networks:
      - sp-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./shinyproxy:/opt/shinyproxy"
volumes:
  pg-data:
  pycharm-data:

# docker-compose down ; docker-compose up --build