## set up the volume first
#  docker volume create pg-data (not necessary)

version: '3.8'

networks:
  sp-net:
    name: sp-net
# # customnetwork for fixed IPAddress (insted of sp-net)
#  customnetwork:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16

services:
  db:
    container_name: postgres-container
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    networks:
      - sp-net
    command: ["postgres", "-c", "log_statement=all"]
#    ports:
#      - 5432:5432
  duplicate-finder:
    container_name: duplicate-finder
    image: bouldermaettel/duplicate-finder
#    ports:
#      - 3838:3838
    networks:
      - sp-net
    depends_on:
      - db
  neraa:
    container_name: neraa
    image: bouldermaettel/neraa
#    ports:
#      - 3939:3939
    networks:
      - sp-net
  shinyproxy:
    container_name: sp-neraa-a848
    build: ./shinyproxy
    ports:
      - 8080:8080
    environment:
      - "WORK_DIR=${PWD}"
    networks:
      - sp-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./shinyproxy:/opt/shinyproxy"
volumes:
  pg-data:

#  pgadmin:
#    container_name: pgadmin4-container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: bouldermaettel@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    networks:
#      - sp-net





# docker kill $(docker ps -q)
# start with: ~/postgres $ docker-compose up
# stop with: ~/postgres $ docker-compose down
# docker-compose down; docker-compose build; docker-compose up
# docker-compose down ; docker-compose build ; docker-compose up