# https://lukesingham.com/shiny-containers-with-shinyproxy/
# for custom templates https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template

proxy:
  default-max-instances: -1
  title: ShinyProxy
  port: 8080
  heartbeat-timeout: 120000
  container-log-path: /container-logs
  template-path: ./templates/2col
  authentication: simple
  admin-groups: admin
  hide-navbar: false
  logo-url: https://raw.githubusercontent.com/bouldermaettel/A848/main/data/SMC40%208.jpg
  landing-page: /
  users:
  - name: brudis
    password: brudis@smc40
    groups: admin
  - name: matthias.mueller
    password: bouldermaettel@smc40
    groups: admin
  - name: anouk.aguirre
    password: legal@smc
    groups: neraa
  - name: neraa
    password: neraa@smc
    groups: neraa_public

  docker:
      internal-networking: true
      container-network: 'sp-net'
  specs:
  - id: neraa
    max_instances: -1
    display-name: NERAA
    description: Anonymization application
    container-cmd: ["R", "-e", "shiny::runApp('/root/app', host = '0.0.0.0', port = 3939)"]
    container-image: bouldermaettel/neraa
    port: 3939
    access-groups: [admin, neraa_legal, neraa_public]
    container-network: "${proxy.docker.container-network}"
    container-volumes: ["/root/app:/mnt", "/root/app/www/training-data:/mnt/training-data"]

logging:
  file:
    log/shinyproxy.log

