# https://lukesingham.com/shiny-containers-with-shinyproxy/
# for custom templates https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template

proxy:
  default-max-instances: -1
  title: ShinyProxy
  port: 8080
  container-log-path: /container-logs
  template-path: ./templates/2col
  authentication: simple
  admin-groups: admin
  hide-navbar: false
  logo-url: https://raw.githubusercontent.com/bouldermaettel/A848/main/data/SMC40%208.jpg
  landing-page: /
  # docker, docker-swarm or kubernetes
#  container-backend: docker
  users:
  - name: matthias.mueller
    password: bouldermaettel@smc40
    groups: admin
  - name: anouk.aguirre
    password: legal@smc
    groups: neraa
  - name: myrtha.naef
    password: illegal@smc
    groups: a848su
  - name: mock_user
    password: 123@abc
    groups: a848
  - name: mock_superuser
    password: 123@abc
    groups: a848su
  docker:
      internal-networking: true
      container-network: 'sp-net'
  specs:
  - id: neraa
    max_instances: -1
    display-name: NERAA
    description: Anonymization application
    container-cmd: ["R", "-e", "shiny::runApp('/root/app', host = '0.0.0.0', port = 3939)"]
    container-image: bouldermaettel/neraa
    port: 3939
    access-groups: [neraa, admin]
    container-network: "${proxy.docker.container-network}"
    container-volumes: ["/root/app:/mnt", "/root/app/www/training-data:/mnt/training-data"]
  - id: A848
    display-name: A848
    description: A848 duplicate finder
    container-cmd: [ "R", "-e", "shiny::runApp('/root/app', host = '0.0.0.0', port = 3838)" ]
    container-image: bouldermaettel/duplicate-finder
    access-groups: [a848su, a848, admin]
    container-network: "${proxy.docker.container-network}"
#    container-volumes: ["/root/app/data:/home/bouldermaettel/Documents/A848data"]
    port: 3838

logging:
  file:
    log/shinyproxy.log

#server:
#  servlet:
#    context-path:  /

# docker-compose down ; docker-compose build ; docker-compose up
